
server:
  port: 8081  # Spring boot Server port

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    driver-class-name: org.h2.Driver

    jpa:
      hibernate:
        ddl-auto: create-drop
      properties:
        hibernate:
          #show_sql: true
          format_sql: true